version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: chat-box-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: chat-box
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      timeout: 20s
      retries: 10

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: chat-box-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - API_PORT=8000
      - HOST=0.0.0.0
      - DATABASE_URL=mysql+pymysql://user:user@mysql:3306/chat-box
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./server:/app
    command:
      [
        "uv",
        "run",
        "uvicorn",
        "main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--reload",
      ]

volumes:
  mysql_data:
