[project]
name = "chat-box-server"
version = "0.1.0"
description = "Chat application backend"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "fastapi>=0.104.0",
    "uvicorn[standard]>=0.24.0",
    "python-dotenv>=1.0.0",
    "dotenv>=0.9.9",
]
